<a href="https://colab.research.google.com/github/DFruktova/01_numpy_Fruktova_Daria.ipynb/blob/main/Fruktova_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №1

In [1]:
# импорт библиотеки и файла
import numpy as np
import csv
from google.colab import files
uploaded = files.upload()


Saving minutes_n_ingredients.csv to minutes_n_ingredients.csv


In [2]:
#1

arr = np.loadtxt("minutes_n_ingredients.csv", delimiter=",", skiprows=1, dtype='int32')
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [3]:
#2 Вычислите среднее значение, минимум, максимум и медиану по каждому из
# столбцов, кроме первого. 
print( "Средние значения:", np.mean(arr[:,1]), ",", np.mean(arr[:,2]))
print( "Максимальные значения:", np.max(arr[:,1]), ",", np.max(arr[:,2]))
print( "Минимальные значения:", np.min(arr[:,1]), ",", np.min(arr[:,2]))
print( "Медианные значения:", np.median(arr[:,1]), ",", np.median(arr[:,2]))

Средние значения: 21601.00169 , 9.05528
Максимальные значения: 2147483647 , 39
Минимальные значения: 0 , 1
Медианные значения: 40.0 , 9.0


In [4]:
#3 Ограничьте сверху значения продолжительности выполнения рецепта
# значением квантиля q0.75

#arr[:,1] = np.clip(arr[:,1], a_min=None, a_max=np.quantile(arr[:,1], .75))
#print(arr)

q75=np.quantile(arr[:,1], .75)
arr[:,1]= np.clip(arr[:,1], 0, q75)
print(arr)


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [5]:
#4 Посчитайте, для скольких рецептов указана продолжительность, равная нулю. 
#Замените для таких строк значение в данном столбце на 1.

count = np.count_nonzero(arr[:,1] == 0)
print("Рецептов с продолжительностью 0:", count)
arr[arr[:,1] == 0 ] = 1


Рецептов с продолжительностью 0: 479


In [6]:
#5 Посчитайте, сколько уникальных рецептов находится в датасете.
print(len(np.unique(arr, axis=1)))

100000


In [7]:
#6 Сколько и каких различных значений кол-ва ингредиентов присутвует в 
#рецептах из датасета?
print("Кол-во уникальных значений:", len (np.unique(arr[:,2])))
print("Эти уникальные значения:", np.unique(arr[:,2]))

Кол-во уникальных значений: 37
Эти уникальные значения: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [8]:
#7 Создайте версию массива, содержащую информацию только о рецептах, состоящих 
#не более чем из 5 ингредиентов.

arr2 = arr[arr[:,2]<=5, :].copy()
print(len(arr2))

17653


In [12]:
#8 Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на
#одну минуту рецепта.Найдите максимальное значение этой величины 
#для всего датасета

avg = np.empty(len(arr))

#avg = np.array(empty)
avg = arr[:,2]/arr[:,1]

print("Максимальное значение:", np.max(avg))

Максимальное значение: 23.0


In [15]:
#9 Вычислите среднее количество ингредиентов для топ-100 рецептов с 
#наибольшей продолжительностью

sorted = arr[arr[:,1].argsort()][::-1] #sort по убыванию
print(np.average(sorted[:,2][:100 ]))

9.96


In [16]:
#10 Выберите случайным образом и выведите информацию о 10 различных рецептах
import random
ind = np.random.randint(len(arr), size=10)
print (arr[ind,:])

[[154221     45     12]
 [484339     65     12]
 [300192     20      6]
 [231675     65     10]
 [199744      5      5]
 [469918     30      5]
 [525677     35     12]
 [177450     38      6]
 [ 69743     45      9]
 [312613     65     10]]


In [22]:
#11 Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.
ing = arr[:,2]
aing = np.average(ing)
print(len (arr[ing<aing])/len(arr)*100)

58.989000000000004


In [24]:
#12 Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 
# минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета 
#с дополнительным столбцом, значениямикоторого являются 1, если рецепт простой, 
#и 0 в противном случае.
e = (arr[:, 1] <= 20) & (arr[:, 2] <= 5) 
easy = np.append(arr, e[:, np.newaxis], axis=1)
print(easy)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


In [25]:
#13 Выведите процент "простых" рецептов в датасете
print(len(easy[easy[:,3]==1])/len(easy)*100)

9.943


In [28]:
#14 
short = arr[:,1]<10
stand = (arr[:,1]>=10) & (arr[:,1]<20)
long = arr[:,1]>=20
b = min(len(arr[short]), len(arr[stand]), len(arr[long]))
new = np.array(((arr[short])[:b], (arr[stand])[:b],(arr[long])[:b] ))
print("Форма полученного массива:", new.shape)

Форма полученного массива: (3, 7588, 3)
